package fase1;

import java.util.HashMap;

public class Car {

	private String marca;
	private String modelo;
	private double fuel;
	private float maxspeed;
	private boolean gasolinera;
	private String[] drive;
	private int tanque;
	//Constructores
	 public Car(String marca, String modelo, double fuel, float maxspeed, boolean gasolinera, String[] drive, int tanque) {
	        this.marca = marca;
	        this.modelo = modelo;
	        this.fuel = fuel;
	        this.maxspeed = maxspeed;
	        this.gasolinera = gasolinera;
	        this.drive = drive;
	        this.tanque = tanque;
	    }
	 public Car() {
		 System.out.println();
	 }
	
	
	
	
	// Setters - Getter autogenerated
	public String getMarca() {
		return marca;
	}
	public void setMarca(String marca) {
		this.marca = marca;
		System.out.println("La marca de tu coche es: "+ marca);
	}
	public String getModelo() {		
		return modelo;
	}
	public void setModelo(String modelo) {
		this.modelo=modelo;
		System.out.println("El modelo de tu vehiculo es: "+modelo);
	}
	
	public int getTanque() {
		return tanque;
	}

	public int setTanque(int tanque) {
		this.tanque = tanque;
		System.out.println("Capacidad tanque combustible: " +tanque + " Litros");
		return tanque;
	}

	public Character conduccion(Character drive) {
		HashMap<Character, String>mecanismo = new HashMap<>();
		mecanismo.put('M' ,"Mecanico");
		mecanismo.put('A', "Automatico");
		String meca = mecanismo.get(drive);
		if(meca != null) {
			System.out.println("Tu vehiculo es: " + meca);
			return drive;
		}else {
			System.out.println("Error");
			return null;
		}
		
	}
	
public void setSpeed(String zona) {
		
		HashMap<String, Integer>velocidad = new HashMap<>();
		velocidad.put("poblado", 50);
		velocidad.put("autovia", 90);
		velocidad.put("autopista", 120);
		
		Integer velocidades = velocidad.get(zona);
		
			if(velocidades != null) {
				System.out.println("La velocidad de tu zona es: " + velocidades + "km/h");
				
			}else {
				System.out.println("Error");
				
			}
		}

	
	
	public double getFuel() {
		return fuel;
	}
	public void setFuel(double fuel) {
		this.fuel = fuel;
		if(fuel>0) {
		System.out.println("Tiene el tanque: "+ fuel + " litros");
	
		}else if (fuel==0 || fuel<0){
			System.out.println("Necesitas llenar el tanque");
		}else {
			System.out.println("Valor incorrecto");
		}
	
	}
	public void refuel() {
		if(fuel==tanque || fuel >= (tanque*0.75)) {
			System.out.println("Tanque lleno");
		}else if(fuel>tanque){
			System.out.println("No puedes tener más gasolina que la capacidad maxima");
		}else if(fuel<=(tanque*0.25)) {
			System.out.println("Necesitas ponerle gasolina");
		}
	}
	
	public float getMaxspeed() {
		return maxspeed;
	}
	public void setMaxspeed(float maxspeed) {
		this.maxspeed = maxspeed;
		System.out.println("La velocidad maxima de tu coche: "+maxspeed);
	}

	public void getSpeed() {
		
	}
}
